### ISSUE TITLE
error when starting coinboard

### ISSUE THREAD

**Issue by Byte1122** [teddylun/coinboard#1]
After $coinboard

Results in:
(node:2621) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'USD' of undefined
(node:2621) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

![error](https://user-images.githubusercontent.com/11861774/33716219-a01ca4ac-db55-11e7-9897-0bdfda5b772b.png)

**Comment by bramkok** [comment]
@teddylun @Redouan29 Same here. Tried `node` v7.9.0 and commented out several api sources.

Also tested with both `npm`  and `yarn`. Maybe you limited the BTC value @ 9999? ;)

**Comment by teddylun** [comment]
@Redouan29 @bramkok node version must >= 8.0, I used 8.6

**Comment by teddylun** [comment]
@Redouan29 @bramkok  Please check the limit of Cryptocompare API usage: https://www.cryptocompare.com/api/#requests, and try again later!
Secondly limit API: https://min-api.cryptocompare.com/stats/rate/second/limit
Hourly limit API: https://min-api.cryptocompare.com/stats/rate/hour/limit
